services:
  postgres:
    image: timescale/timescaledb:2.5.1-pg14
    container_name: postgres-metabase
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-metabase
    environment:
      PGADMIN_DEFAULT_EMAIL: root@metroscope.tech
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./docker-pgadmin-servers.json:/pgadmin4/servers.json
  metabase:
    #You have to create the metabase DB with the right user and permission in the postgres, befort starting
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5444
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: host.docker.internal
    ports:
      - "5051:3000"
